name: auto-sync
run-name: Auto Sync
on:
  # Runs every day at 4:00am
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  read-tournament-ids:
    name: Read Tournament Id List
    runs-on: ubuntu-20.04
    outputs:
      TOURNAMENT_IDS: ${{ steps.output.outputs.TOURNAMENT_IDS }}
    steps:
      - uses: actions/checkout@v3
      - id: output
        name: Output id list
        run: echo "TOURNAMENT_IDS=$(cat auto-tournaments.txt | tr '\n' ' ')" >> "$GITHUB_OUTPUT"

  read-hub-ids:
    name: Read Hub Id List
    runs-on: ubuntu-20.04
    outputs:
      HUB_IDS: ${{ steps.output.outputs.HUB_IDS }}
    steps:
      - uses: actions/checkout@v3
      - id: output
        name: Output id list
        run: echo "HUB_IDS=$(cat auto-hubs.txt | tr '\n' ' ')" >> "$GITHUB_OUTPUT"

  extract-hubs:
    name: Extract Hubs
    uses: ./.github/workflows/extract-hubs.yml
    needs: read-hub-ids
    with:
      HUB_IDS: ${{ needs.read-hub-ids.outputs.HUB_IDS }}
    secrets:
      START_GG_API_KEY: ${{ secrets.START_GG_API_KEY }}

  read-hub-tournament-ids:
    name: Read Tournament Ids From Hubs
    runs-on: ubuntu-20.04
    needs: extract-hubs
    outputs:
      TOURNAMENT_IDS: ${{ steps.output.outputs.TOURNAMENT_IDS }}
    steps:
      - name: Download start.gg output
        uses: actions/download-artifact@v4
        with:
          name: start-gg-hubs.json
      - id: output
        name: Output id list
        run: echo "TOURNAMENT_IDS=$(jq --raw-output '.[].tournaments[].slug' < start-gg-hubs.json | tr '\n' ' ')" >> "$GITHUB_OUTPUT"

  extract-tournaments:
    name: Extract Tournaments
    uses: ./.github/workflows/extract-tournaments.yml
    needs:
      - read-tournament-ids
      - read-hub-tournament-ids
    with:
      TOURNAMENT_IDS: ${{ needs.read-tournament-ids.outputs.TOURNAMENT_IDS }} ${{ needs.read-hub-tournament-ids.outputs.TOURNAMENT_IDS }}
    secrets:
      START_GG_API_KEY: ${{ secrets.START_GG_API_KEY }}

  sync-website:
    name: Sync Website
    uses: ./.github/workflows/sync-website.yml
    needs: extract-tournaments
    secrets:
      KCFGC_DEPLOY_KEY: ${{ secrets.KCFGC_DEPLOY_KEY }}

  workflow-keepalive:
    name: Disable Workflow Inactivity
    if: github.event_name == 'schedule'
    runs-on: ubuntu-20.04
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1.2.1
